title: werewolf. world <img src="image/0.1/master.jpg" alt="master" title="master">
description: werewolf.world is a protocol for a game of Werewolf
show_downloads: false
google_analytics: UA-108489922-1
